import customtkinter as ctk
from tkinter import filedialog
from customtkinter import CTkImage
from PIL import Image, ImageTk
from detect import predict_image

app = ctk.CTk()
app.title("Deepfake Detector")
app.geometry("600x700")
app.configure(fg_color="#e1ebfc")
app.iconbitmap("icon.ico")


image_label = ctk.CTkLabel(app, text="", font=("Arial", 16))
image_label.pack(pady=50)

result_label = ctk.CTkLabel(app, text="The Image Result : ", font=("bold", 18), text_color="black")
result_label.pack(pady=10)


selected_image_path = None
img_ctk = None

def choose_image():
    global selected_image_path, img_ctk

    file_path = filedialog.askopenfilename(filetypes=[("Image Files", "*.jpg *.jpeg *.png")])
    if file_path:
        selected_image_path = file_path

        img = Image.open(file_path)

        img_ctk = CTkImage(light_image=img, size=(300, 300))
        image_label.configure(image=img_ctk, text="")
        image_label.image = img_ctk

def analyze_image():
    if selected_image_path:
        print("Analyzing:", selected_image_path)
        label, confidence = predict_image(selected_image_path)
        print(f"Result: {label} ({confidence * 100:.2f}%)")
        result_label.configure(text=f"{label} ({confidence * 100:.2f}%)")
    else:
        print("No image selected!")
        result_label.configure(text="Please choose an image first.")

choose_btn = ctk.CTkButton(
    app, text="Choose Picture", font=ctk.CTkFont("Arial", 15),
    command=choose_image, width=200, corner_radius=0,
    border_color="white", border_width=3, height=50,
    fg_color="black", text_color="red"
)
choose_btn.pack(pady=10)

# Analyze button
analyze_btn = ctk.CTkButton(
    app, text="analyzing", font=ctk.CTkFont("Arial", 15),
    command=analyze_image, width=200, corner_radius=0,
    border_color="white", border_width=3, height=50,
    fg_color="black", text_color="red"
)
analyze_btn.pack(pady=30)

description_label = ctk.CTkLabel(
    app,
    text="This program uses AI to detect fake or manipulated images.\nIt helps identify content generated by deepfake tools.",
    wraplength=550,
    justify="center",
    font=("Arial", 14),
    text_color="#AAAAAA"
)
description_label.pack(pady=30, side="bottom")
app.mainloop()
